spring:
  jpa:
    properties:
      hibernate:
        default_schema: penger
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  liquibase:
    default-schema: penger
    change-log: classpath:/database/db.changelog.xml
