spring:
  datasource:
    initialization-mode: always
    platform: h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    properties:
      hibernate:
        default_schema: penger
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  liquibase:
    default-schema: penger
    change-log: classpath:/database/db.changelog.xml
